# Last reviewed: 2026-01-20
name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Navigate to '...'
        2. Click on '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages if applicable).
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Impacts functionality but has workaround
        - High - Blocks functionality, no workaround
        - Critical - Security issue or data loss
      default: 1
    validations:
      required: true

  - type: input
    id: technology
    attributes:
      label: Technology/Runtime Version
      description: If applicable, specify the technology and version.
      placeholder: "e.g., .NET 10, Node.js 22.x, Python 3.12"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide additional environment details
      placeholder: |
        - OS: Windows 11 / macOS 15 / Ubuntu 24.04
        - Browser: Chrome 130 / Edge / Firefox
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output or stack traces.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. Drag and drop images here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
