# Last reviewed: 2026-01-14
name: Documentation
description: Report documentation issues or request documentation improvements
title: "[Docs]: "
labels: ["type:docs", "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What kind of documentation change is needed?
      options:
        - Missing documentation
        - Incorrect information
        - Outdated content
        - Unclear explanation
        - Typo or grammar fix
        - New example needed
        - API reference update
      default: 0
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation that needs attention?
      placeholder: "e.g., README.md, docs/getting-started.md, API reference for UserService"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What does the documentation currently say (if applicable)?
      placeholder: "Quote or describe the current content..."

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should the documentation say instead?
      placeholder: "Describe the improvement or correction needed..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or references

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR with this documentation change
