# Last reviewed: 2026-01-16
name: .NET Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION#v}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }}

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release -p:Version=${{ steps.version.outputs.version }} --output ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: packages
          path: ./artifacts/*.nupkg
          retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: packages
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ needs.build.outputs.version }}
          tag_name: v${{ needs.build.outputs.version }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease || false }}
          files: ./artifacts/*.nupkg

      # Uncomment to push to NuGet.org
      # - name: Push to NuGet
      #   run: |
      #     dotnet nuget push ./artifacts/*.nupkg \
      #       --api-key ${{ secrets.NUGET_API_KEY }} \
      #       --source https://api.nuget.org/v3/index.json \
      #       --skip-duplicate
